// chrome-extension/src/popup/App.js - COMPLETELY UPDATED WITH YOUR DESIGN
import React, { useState, useEffect } from 'react';
import SummaryView from './SummaryView.jsx';
import MindMapView from './MindMapView.jsx';
import HistoryView from './HistoryView.jsx';
import { getSelectedText } from '../utils/api.js';
import { Brain, FileText, Network, History, Copy, Download, Zap, BookOpen, GraduationCap, Sparkles } from 'lucide-react';

const App = () => {
  const [selectedText, setSelectedText] = useState('');
  const [activeView, setActiveView] = useState('summary'); // 'summary', 'mindmap', 'history'
  const [loading, setLoading] = useState(false);
  const [generatedContent, setGeneratedContent] = useState(null);

  useEffect(() => {
    loadSelectedText();
  }, []);

  const loadSelectedText = async () => {
    try {
      const text = await getSelectedText();
      if (text && text.length > 10) {
        setSelectedText(text);
      } else {
        // Fallback placeholder text
        setSelectedText("No text selected. Please select text on a webpage and right-click 'Generate with SynapseMind'.");
      }
    } catch (error) {
      console.error("Error loading selected text:", error);
      setSelectedText("Error loading selected text. Please try selecting text again.");
    }
  };

  const handleGenerate = async (type, level) => {
    setLoading(true);
    setGeneratedContent(null);
    
    // Simulate API call delay
    setTimeout(() => {
      if (type === 'summary') {
        const mockSummaries = {
          quick: "This is a quick AI-generated summary of the selected text, highlighting the main points concisely.",
          detailed: "This is a detailed paragraph-style summary generated by SynapseMind using advanced AI. It provides comprehensive coverage of the selected text's key themes, arguments, and implications.",
          academic: "Academic Summary:\n• Primary Thesis: Core argument presented\n• Methodology: Approach used in analysis\n• Key Findings: Major discoveries or points\n• Implications: Practical applications\n• Limitations: Scope boundaries noted"
        };
        setGeneratedContent({
          type: 'summary',
          content: mockSummaries[level],
          level: level
        });
      } else if (type === 'mindmap') {
        setGeneratedContent({
          type: 'mindmap',
          content: {
            nodes: [
              { id: '1', label: 'Main Concept', type: 'main' },
              { id: '2', label: 'Sub Concept A', type: 'sub' },
              { id: '3', label: 'Sub Concept B', type: 'sub' },
              { id: '4', label: 'Detail 1', type: 'detail' },
              { id: '5', label: 'Detail 2', type: 'detail' },
              { id: '6', label: 'Related Topic', type: 'sub' }
            ],
            edges: [
              { source: '1', target: '2', label: 'includes' },
              { source: '1', target: '3', label: 'includes' },
              { source: '2', target: '4', label: 'supports' },
              { source: '3', target: '5', label: 'supports' },
              { source: '1', target: '6', label: 'related to' }
            ]
          }
        });
      }
      setLoading(false);
    }, 1200);
  };

  const handleCopy = (text) => {
    navigator.clipboard.writeText(text)
      .then(() => {
        // Show temporary success message
        const originalText = document.getElementById('copyBtn').innerText;
        document.getElementById('copyBtn').innerText = 'Copied!';
        setTimeout(() => {
          document.getElementById('copyBtn').innerText = originalText;
        }, 2000);
      })
      .catch(err => console.error('Copy failed:', err));
  };

  const handleExport = (content, filename) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const renderSelectedTextPreview = () => {
    const isPlaceholder = selectedText.includes('No text selected') || selectedText.includes('Error loading');
    
    return (
      <div className="mb-4">
        <div className="flex items-center justify-between mb-2">
          <span className="text-sm font-medium text-slate-300">Selected Text</span>
          <button
            onClick={loadSelectedText}
            className="text-xs text-slate-400 hover:text-slate-300"
          >
            Refresh
          </button>
        </div>
        <div className={`p-3 rounded-lg ${isPlaceholder ? 'bg-slate-800/50' : 'bg-slate-800'} border border-slate-700`}>
          <p className={`text-sm ${isPlaceholder ? 'text-slate-400 italic' : 'text-slate-200'} line-clamp-3`}>
            {selectedText.length > 200 ? selectedText.substring(0, 200) + '...' : selectedText}
          </p>
          {!isPlaceholder && (
            <div className="flex justify-between items-center mt-2 text-xs text-slate-400">
              <span>{selectedText.length} characters</span>
              <button
                onClick={() => handleCopy(selectedText)}
                className="flex items-center gap-1 hover:text-slate-300"
              >
                <Copy size={12} /> Copy
              </button>
            </div>
          )}
        </div>
      </div>
    );
  };

  return (
    <div className="w-[380px] min-h-[500px] p-4 bg-gradient-to-br from-slate-900 to-slate-800 text-white">
      {/* Header */}
      <header className="flex items-center gap-3 mb-6">
        <div className="p-2 bg-gradient-to-br from-blue-500 to-purple-500 rounded-lg">
          <Brain className="text-white" size={24} />
        </div>
        <div>
          <h1 className="text-xl font-bold bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
            SynapseMind
          </h1>
          <p className="text-xs text-slate-400">AI-Powered Learning Companion</p>
        </div>
      </header>

      {/* Main Content Area */}
      <div className="space-y-4">
        {/* Selected Text Preview */}
        {renderSelectedTextPreview()}

        {/* Navigation Tabs */}
        <div className="flex border-b border-slate-700">
          <button
            className={`flex-1 py-2 text-center font-medium ${activeView === 'summary' ? 'text-blue-400 border-b-2 border-blue-400' : 'text-slate-400 hover:text-slate-300'}`}
            onClick={() => setActiveView('summary')}
          >
            <span className="flex items-center justify-center gap-2">
              <FileText size={16} /> Summary
            </span>
          </button>
          <button
            className={`flex-1 py-2 text-center font-medium ${activeView === 'mindmap' ? 'text-blue-400 border-b-2 border-blue-400' : 'text-slate-400 hover:text-slate-300'}`}
            onClick={() => setActiveView('mindmap')}
          >
            <span className="flex items-center justify-center gap-2">
              <Network size={16} /> Mind Map
            </span>
          </button>
          <button
            className={`flex-1 py-2 text-center font-medium ${activeView === 'history' ? 'text-blue-400 border-b-2 border-blue-400' : 'text-slate-400 hover:text-slate-300'}`}
            onClick={() => setActiveView('history')}
          >
            <span className="flex items-center justify-center gap-2">
              <History size={16} /> History
            </span>
          </button>
        </div>

        {/* Content Views */}
        <div className="min-h-[300px]">
          {activeView === 'summary' && (
            <SummaryView 
              selectedText={selectedText}
              loading={loading}
              generatedContent={generatedContent}
              onGenerate={handleGenerate}
              onCopy={handleCopy}
              onExport={handleExport}
            />
          )}
          
          {activeView === 'mindmap' && (
            <MindMapView 
              selectedText={selectedText}
              loading={loading}
              generatedContent={generatedContent}
              onGenerate={handleGenerate}
              onExport={handleExport}
            />
          )}
          
          {activeView === 'history' && (
            <HistoryView />
          )}
        </div>
      </div>

      {/* Footer */}
      <footer className="mt-6 pt-4 border-t border-slate-700 text-center">
        <p className="text-xs text-slate-400">MVP Demo • Chrome Extension Popup</p>
        <div className="flex justify-center gap-4 mt-2 text-xs text-slate-500">
          <span>Select text → Right-click → SynapseMind</span>
        </div>
      </footer>
    </div>
  );
};

export default App;